// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.medroid.domain;

import com.medroid.domain.DoctorMessages;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DoctorMessages_Roo_Configurable {
    
    declare @type: DoctorMessages: @Configurable;
    
}
